export const ideasList = [
    {
        title: "Morning Coffee ☕",
        desc: "Film 3 quick shots of your morning coffee ritual.",
        music: "Chill Vibes Track",
        duration: "15s",
        tags: ["morning", "coffee", "lifestyle"],
        difficulty: "Easy",
        shots: 3,
        tip: "Best filmed in portrait mode near a window with natural light.",
        shotsDetails: [
            { text: "Pour coffee", emoji: "☕" },
            { text: "First sip", emoji: "😋" },
            { text: "Smile", emoji: "😊" },
        ],
    },
    {
        title: "City Walk 🚶‍♂️",
        desc: "Film your short city walk in 3 shots.",
        music: "Urban Beat",
        duration: "20s",
        tags: ["city", "walk", "travel"],
        difficulty: "Easy",
        shots: 3,
        tip: "Capture details: footsteps, moving traffic, wide street shots.",
        shotsDetails: [
            { text: "Your shoes", emoji: "👟" },
            { text: "Street view", emoji: "🏙️" },
            { text: "Landmark", emoji: "📍" },
        ],
    },
    {
        title: "Dance Break 💃",
        desc: "Show 5 seconds of your favorite dance move.",
        music: "Trending TikTok Track",
        duration: "10s",
        tags: ["dance", "fun", "trend"],
        difficulty: "Medium",
        shots: 1,
        tip: "Place camera steady — full body in frame works best.",
        shotsDetails: [{ text: "Your move", emoji: "💃" }],
    },
    {
        title: "Cooking Fun 🍳",
        desc: "Film your cooking in 3 stages.",
        music: "Upbeat Acoustic",
        duration: "30s",
        tags: ["cooking", "food", "home"],
        difficulty: "Easy",
        shots: 3,
        tip: "Film close-ups of ingredients for texture.",
        shotsDetails: [
            { text: "Ingredients", emoji: "🥦" },
            { text: "Cooking", emoji: "🍳" },
            { text: "Final dish", emoji: "🍽️" },
        ],
    },
    {
        title: "Gym Progress 🏋️",
        desc: "Capture your workout routine in 3 shots.",
        music: "Epic Motivation",
        duration: "25s",
        tags: ["fitness", "gym", "motivation"],
        difficulty: "Medium",
        shots: 3,
        tip: "Use tripod or ask a friend for stable shots.",
        shotsDetails: [
            { text: "Warm-up", emoji: "🤸" },
            { text: "Main exercise", emoji: "🏋️" },
            { text: "Flex / result", emoji: "💪" },
        ],
    },
    {
        title: "Study Vibes 📚",
        desc: "Show your cozy study setup in 3 shots.",
        music: "Lo-Fi Beats",
        duration: "15s",
        tags: ["study", "aesthetic", "lifestyle"],
        difficulty: "Easy",
        shots: 3,
        tip: "Add candles or warm lights for cozy vibes.",
        shotsDetails: [
            { text: "Desk setup", emoji: "🖥️" },
            { text: "Taking notes", emoji: "✍️" },
            { text: "Coffee mug", emoji: "☕" },
        ],
    },
    {
        title: "Travel Snapshot ✈️",
        desc: "Highlight your trip in 3 fast clips.",
        music: "Cinematic Chill",
        duration: "20s",
        tags: ["travel", "adventure", "explore"],
        difficulty: "Easy",
        shots: 3,
        tip: "Mix wide shots with close details.",
        shotsDetails: [
            { text: "Transport view", emoji: "✈️" },
            { text: "Nature / cityscape", emoji: "🌄" },
            { text: "Local food", emoji: "🍜" },
        ],
    },
    {
        title: "Pet Day 🐶",
        desc: "Show off your pet’s cuteness in 3 shots.",
        music: "Playful Pop",
        duration: "15s",
        tags: ["pets", "cute", "fun"],
        difficulty: "Easy",
        shots: 3,
        tip: "Film at their eye level for best effect.",
        shotsDetails: [
            { text: "Pet looking at camera", emoji: "👀" },
            { text: "Playing", emoji: "🎾" },
            { text: "Sleeping", emoji: "💤" },
        ],
    },
    {
        title: "Before / After ✨",
        desc: "Show transformation in 2 shots.",
        music: "Trending Remix",
        duration: "12s",
        tags: ["trend", "glowup", "transformation"],
        difficulty: "Medium",
        shots: 2,
        tip: "Use transition for smooth change.",
        shotsDetails: [
            { text: "Before", emoji: "😐" },
            { text: "After", emoji: "🔥" },
        ],
    },
    {
        title: "Sunset Mood 🌅",
        desc: "Film the sunset in 2 cinematic shots.",
        music: "Chill Cinematic",
        duration: "12s",
        tags: ["nature", "sunset", "aesthetic"],
        difficulty: "Easy",
        shots: 2,
        tip: "Use slow pan for smooth movement.",
        shotsDetails: [
            { text: "Sunset wide view", emoji: "🌅" },
            { text: "Silhouette", emoji: "👤" },
        ],
    },
    {
        title: "Fashion Fit 👗",
        desc: "Show today’s outfit in 3 angles.",
        music: "Trendy Fashion Beat",
        duration: "15s",
        tags: ["fashion", "OOTD", "style"],
        difficulty: "Medium",
        shots: 3,
        tip: "Film with mirror or ask a friend.",
        shotsDetails: [
            { text: "Full body", emoji: "🪞" },
            { text: "Accessories", emoji: "⌚" },
            { text: "Shoes", emoji: "👠" },
        ],
    },
    {
        title: "Quick Recipe 🥗",
        desc: "Show a recipe in 3 quick steps.",
        music: "Fast Beat",
        duration: "20s",
        tags: ["food", "cooking", "DIY"],
        difficulty: "Easy",
        shots: 3,
        tip: "Time-lapse works great for cooking.",
        shotsDetails: [
            { text: "Ingredients", emoji: "🥑" },
            { text: "Cooking process", emoji: "🍳" },
            { text: "Final plate", emoji: "🍴" },
        ],
    },
    {
        title: "Unboxing 🎁",
        desc: "Unbox your new item in 3 shots.",
        music: "Exciting Trap",
        duration: "20s",
        tags: ["unboxing", "tech", "trend"],
        difficulty: "Easy",
        shots: 3,
        tip: "Film hands + reactions.",
        shotsDetails: [
            { text: "Box", emoji: "📦" },
            { text: "Opening", emoji: "✂️" },
            { text: "Product reveal", emoji: "✨" },
        ],
    },
    {
        title: "Friendship Moments 👯",
        desc: "Capture 3 fun moments with friends.",
        music: "Happy Pop",
        duration: "20s",
        tags: ["friends", "fun", "lifestyle"],
        difficulty: "Easy",
        shots: 3,
        tip: "Show natural laughs, not staged.",
        shotsDetails: [
            { text: "Walking together", emoji: "🚶‍♂️🚶‍♀️" },
            { text: "Laughing", emoji: "😂" },
            { text: "Cheers / hug", emoji: "🥂" },
        ],
    },
    {
        title: "Street Food Hunt 🌮",
        desc: "Try local street food in 3 shots.",
        music: "Energetic World Beat",
        duration: "25s",
        tags: ["food", "travel", "culture"],
        difficulty: "Medium",
        shots: 3,
        tip: "Focus on sizzling and textures.",
        shotsDetails: [
            { text: "Street stall", emoji: "🍜" },
            { text: "Cooking in action", emoji: "🔥" },
            { text: "Tasting", emoji: "🤤" },
        ],
    },
];
